[TWITTER]
API_KEY = "C3bTKfZL8RLEVCwxnnMYZBDPB"
API_SECRET_KEY = "ou271ZijRv6vmwSUvI4OHCwXdBSQoJsM81Xrhc0YtXnlwKWSCD"
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAABnJdAEAAAAAPnkkg17QiqYGsnyG%2FMCMGgTLpl8%3DCYPSgdHeKcATOzuVDMcfc08u1MtrI59o9lEzQ6CUBMOOSvjEDt"
REAL_USER_ID = "1525896119376551937"
FAKE_USER_ID = "913293734"
CLIENT_ID = "aW02bG9LNzBKbW1rU1FST2ZWaUo6MTpjaQ"
CLIENT_SECRET = "Qx5op8DuOWFqgckdw_Ptr01ro9axkgTT8_G41Q7cpmlU5iMA9d"
